server:
  port: 8089
#  servlet:
#    context-path: /api/profile
#management:
#  server:
#    port: 8189
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    hikari:
      schema: profile
#  jpa:
#    hibernate:
#      ddl-auto: validate
  liquibase:
    default-schema: profile
    change-log: db/changelog/db.changelog-master.yaml
    enabled: false
    drop-first: false
#  application:
#    name: profile-app
